### ISSUE TITLE
encoding

### ISSUE THREAD

**Issue by Shane-at-the-Library** [JeffXue/WebLogParser#4]
C:\Users\Shane\source\repos\web-log-parser\bin>python start.py
Traceback (most recent call last):
  File "start.py", line 12, in <module>
    from config import config
  File "C:\Users\Shane\source\repos\web-log-parser\bin\config.py", line 54, in <module>
    config = Config('../conf/config.ini')
  File "C:\Users\Shane\source\repos\web-log-parser\bin\config.py", line 11, in __init__
    all_config.readfp(cfg_file)
  File "C:\Python38\lib\configparser.py", line 763, in readfp
    self.read_file(fp, source=filename)
  File "C:\Python38\lib\configparser.py", line 718, in read_file
    self._read(f, source)
  File "C:\Python38\lib\configparser.py", line 1017, in _read
    for lineno, line in enumerate(fp, start=1):
  File "C:\Python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 493: character maps to <undefined>

**Comment by JeffXue** [comment]
@Shane-at-the-Library   Is it convenient to provide your config.ini file?

**Comment by mondayice** [comment]
2020-06-07 12:45:39.863447  Start parse file : webplug.log
Traceback (most recent call last):
  File "C:/Users/Mondayice/Desktop/123/web-log-parser/bin/start.py", line 382, in main
    parse_log_file(target_file, log_format)
  File "C:/Users/Mondayice/Desktop/123/web-log-parser/bin/start.py", line 232, in parse_log_file
    response_avg = int(pv / len(set(times)))
ZeroDivisionError: division by zero

**Comment by mondayice** [comment]
2020-06-07 12:46:44.981237  Start parse file : access.log
Traceback (most recent call last):
  File "C:/Users/Mondayice/Desktop/123/web-log-parser/bin/start.py", line 382, in main
    parse_log_file(target_file, log_format)
  File "C:/Users/Mondayice/Desktop/123/web-log-parser/bin/start.py", line 232, in parse_log_file
    response_avg = int(pv / len(set(times)))
ZeroDivisionError: division by zero

**Comment by JeffXue** [comment]
> 2020-06-07 12:46:44.981237 Start parse file : access.log
> Traceback (most recent call last):
> File "C:/Users/Mondayice/Desktop/123/web-log-parser/bin/start.py", line 382, in main
> parse_log_file(target_file, log_format)
> File "C:/Users/Mondayice/Desktop/123/web-log-parser/bin/start.py", line 232, in parse_log_file
> response_avg = int(pv / len(set(times)))
> ZeroDivisionError: division by zero

you should check log-pattern and log-format in config.ini file. it seem like can not found the datetime  in the log.

**Comment by metaStor** [comment]
try to save config.ini in ASICII encoding.

**Comment by cnfreiheit** [comment]
This is a windows system utf encoding problem, 'bom' will be added in windows, so can't read. However ,the 'open' function can't define utf-8, so need change 'open' to 'codecs.open' in config.py and start.py , define it to utf-8.
`with codecs.open(config_file, 'r','utf-8') as cfg_file:`  (config.py )
`with codecs.open('../data/' + target_file, 'r','utf-8') as f:`(start.py)

**Comment by JeffXue** [comment]
fix in  904f838ddce5defc8715f2e444063520b7b0d612 commit
