### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by fnatic0606** [JeffXue/WebLogParser#7]
2022-06-08 14:07:15.899174  Start parse file : access_http.log
Traceback (most recent call last):
  File "/opt/log_analyse/web-log-parser-master/bin/start.py", line 381, in main
    parse_log_file(target_file, log_format)
  File "/opt/log_analyse/web-log-parser-master/bin/start.py", line 232, in parse_log_file
    response_avg = int(pv / len(set(times)))
ZeroDivisionError: division by zero

**Comment by JeffXue** [comment]
按照当前的报错信息，应该是解析到的时间字段数据为空，可以检查下正则是否匹配到对应的数据
